name: CryptoHopper Trade Alerts

on:
  schedule:
    - cron: "*/2 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install requests
          pip install pydrive2

      - name: Save client_secrets.json
        run: |
          echo "${{ secrets.CLIENT_SECRETS_JSON }}" > client_secrets.json

      - name: Run script
        env:
          HOPPER_ID: ${{ secrets.HOPPER_ID }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: python script.py

      - name: Commit updated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add last_trade_id.txt trades_log.txt saved_trade_ids.txt
          git commit -m "Update trade logs [skip ci]" || echo "No changes"
          git push
